language: node_js
sudo: false
node_js:
  - '5.12.0'
cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  postgresql: '9.4'
services:
  - postgresql
before_script:
  - createuser --createdb --login pokedex_tracker_user
  - createdb --owner pokedex_tracker_user pokedex_tracker
  - yarn db:migrate
script:
  - yarn test
  - yarn lint
after_script:
  - yarn coveralls
